### ISSUE TITLE
centos-8 has different checksum file names

### ISSUE THREAD

**Issue by Smithx10** [joyent/mi-centos-hvm#5]
https://mirrors.edge.kernel.org/centos/8/isos/x86_64/
CHECKSUM                                           12-Jun-2020 22:42     485
CHECKSUM.asc                                       19-Jun-2020 17:10     811

https://mirrors.edge.kernel.org/centos/7/isos/x86_64/
sha256sum.txt                                      22-Apr-2020 22:17     598
sha256sum.txt.asc                                  22-Apr-2020 22:18    1458

**Comment by Smithx10** [comment]
Nevermind it is in the overrides.

**Comment by Smithx10** [comment]
Had to change overrides to handle CHECKSUM and CHECKSUM.asc 

```

# Sets global variables iso_file and iso_sha
get_iso_file_sha() {
    local file

    if [[ -n $iso_file ]]; then
        return
    fi

    echo "Checking to see if we have the iso for $distro $release:"
    for file in CHECKSUM CHECKSUM.asc; do
         curl -s -o $iso_dir/$file $ISO_URL/$file
    done
    gpg --verify $iso_dir/$file

    # As new dot releases come out, the name of the iso file changes according
    # to a predictable pattern.  The sha256sums.txt file contains the proper
    # name.
    eval $(awk '$2 ~ "^.CentOS-8.\*-x86_64-dvd1.iso.$" {
            gsub("[()]", "", $2);
                    printf("iso_sha=%s; iso_file=%s;", $NF, $2);
        }' $iso_dir/CHECKSUM)
    if [[ -z $iso_file || -z $iso_sha ]]; then
        echo "$0: unable to determine ISO file and/or sha256" 1>&2
        exit 1
    fi
}

```

**Comment by timfoster** [comment]
Yep, I think this is https://github.com/joyent/mi-centos-hvm/pull/4 as yet, unreviewed.
